server:
  port: 7003

spring:
  application:
    name: recommendation-service

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: recommendation-db

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG