spring.application.name=recommendation-service
server.port=7003
logging.level.com.example=INFO

spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=recommendation-db
spring.data.mongodb.auto-index-creation=true